In [1]:
import spacy
from spacy import displacy

In [2]:
nlp = spacy.load('en_core_web_sm')

In [3]:
text = "Apple, This is first sentence. and Google this is another one. here 3rd one is"

In [4]:
doc = nlp(text)

In [5]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd one is

In [6]:
for token in doc:
    print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
one
is


In [7]:
sent = nlp.create_pipe('sentencizer')

In [8]:
nlp.add_pipe(sent, before='parser')

In [9]:
doc = nlp(text)

In [10]:
for sent in doc.sents:
    print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd one is


In [11]:
from spacy.lang.en.stop_words import STOP_WORDS

In [12]:
stopwords = list(STOP_WORDS)

In [13]:
print(stopwords)

['well', 'do', 'myself', '’s', 'themselves', 'ever', 'next', 'another', "'m", 'our', 'least', 'five', 'go', 'third', 'its', 'back', 'have', 'otherwise', 'many', 'one', 'these', 'via', 'might', 'their', 'must', 'amongst', 'twenty', 'been', 'too', 'did', 'seem', 'for', 'nowhere', 'towards', '‘d', 'or', '’d', 'therefore', 'himself', 'could', 'but', 'at', 'become', 'moreover', 'then', 'anyhow', 'itself', 'herself', 'although', 'ours', 'be', 'due', 'yourselves', 'being', 'besides', 'latter', 'both', 'a', 'my', 'across', 'nor', 'not', 'which', 'none', 'less', 'every', 'please', 'perhaps', 'doing', '‘re', 'should', 'beside', 'until', 'seemed', 'was', 'and', 'latterly', 'since', 'whom', '’ll', 'else', 'during', 'often', 'your', 'just', 'used', 'four', 'full', 'twelve', 'using', 'sixty', 'everyone', 'she', 'three', 'still', 'throughout', "'d", 'no', 'meanwhile', 'everywhere', 'some', 'as', 'how', 'afterwards', 'everything', 'sometimes', 'of', 'about', 'indeed', 'by', 'with', 'hers', 'mine', 'si

In [14]:
len(stopwords)

326

In [15]:
for token in doc:
    if token.is_stop == False:
        print(token)

Apple
,
sentence
.
Google
.
3rd


In [16]:
doc = nlp('run runs running runner')

In [17]:
for lem in doc:
    print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner


In [18]:
doc = nlp('All is well at your end!')

In [20]:
for token in doc:
    print(token.text, token.pos_)

All DET
is AUX
well ADJ
at ADP
your DET
end NOUN
! PUNCT


In [21]:
displacy.render(doc, style = 'dep')

In [22]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

In [23]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [24]:
displacy.render(doc, style = 'ent')

In [25]:
import pandas as pd

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [27]:
data_yelp = pd.read_csv('datasets/yelp_labelled.txt', sep='\t', header = None)

In [28]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [29]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name

In [30]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [31]:
data_yelp.shape

(1000, 2)

In [32]:
data_amazon = pd.read_csv('datasets/amazon_cells_labelled.txt', sep = '\t', header = None)
data_amazon.columns = columns_name

In [33]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [34]:
data_amazon.shape

(1000, 2)

In [35]:
data_imdb = pd.read_csv('datasets/imdb_labelled.txt', sep = '\t', header = None)

In [36]:
data_imdb.columns = columns_name

In [37]:
data_imdb.shape

(748, 2)

In [38]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [39]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [40]:
data.shape

(2748, 2)

In [41]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [42]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [43]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [44]:
import string

In [45]:
punct = string.punctuation

In [46]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [47]:
def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [48]:
text_data_cleaning("    Hello how are you. Like this video")

['hello', 'like', 'video']

In [49]:
from sklearn.svm import LinearSVC

In [50]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()

In [51]:
X = data['Review']
y = data['Sentiment']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [53]:
X_train.shape, X_test.shape

((2198,), (550,))

In [54]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [55]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x000001D4A75AA840>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_inter

In [56]:
y_pred = clf.predict(X_test)

In [57]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.81      0.79       285
           1       0.78      0.74      0.76       265

    accuracy                           0.78       550
   macro avg       0.78      0.78      0.78       550
weighted avg       0.78      0.78      0.78       550



In [58]:
confusion_matrix(y_test, y_pred)

array([[230,  55],
       [ 68, 197]], dtype=int64)

In [59]:
clf.predict(['Wow, this is amzing lesson'])

array([1], dtype=int64)

In [60]:
clf.predict(['Wow, this sucks'])

array([0], dtype=int64)